name: Response Time CI
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  response-time:
    name: Log response times
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log response times
        uses: upptime/uptime-monitor@master
        with:
          command: response-time
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
