name: Uptime CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  uptime:
    name: Check uptime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run uptime check
        uses: upptime/uptime-monitor@master
        with:
          command: update
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          NOTIFICATION_SLACK: ${{ secrets.NOTIFICATION_SLACK }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
